apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queue-component
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://sb-giovani.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=wICmqvjeN+QfEzj53bj8f3mIN4GgqfBsYFkZ/tFDqdg="