apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: Basket
  namespace: nwd
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: keyPrefix
    value: basket
  # type: state.azure.cosmosdb
  # version: v1
  # initTimeout: 5m
  # metadata:
  # - name: url
  #   value: https://localhost:8081
  # - name: masterKey
  #   value: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
  # - name: database
  #   value: BasketDB
  # - name: collection
  #   value: Basket
  # - name: partitionKey
  #   value: id
scopes:
- nwd-basket-api