apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nwd-orders.order
  namespace: nwd
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: keyPrefix
    value: order
scopes:
- nwd-orders-api