apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nwd-inventory-inventoryprocessoractor
  namespace: nwd
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
  - name: keyPrefix
    value: InventoryProcessorActor
  - name: actorStateStore
    value: "true"
scopes:
- nwd-inventory-api