apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queue-service
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://sb-giovani.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=aMrP0A02LVrcsTagMmscLy8kBac2Sd9iQv5XOBq4MQY="