# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: 
      DAPR-LAB

steps:

- task: AzurePowerShell@5
  displayName: 'Deploy infrastructure'
  name: 'stepDeployInfrastructure'
  inputs:
    azureSubscription: 'azuredevops-giovanidecusati-spn'
    ScriptType: 'InlineScript'
    Inline: |
      $deploymentArgs = @{
          SubscriptionId    = '$(SubscriptionId)'
          ResourceGroupName = '$(ResourceGroupName)'
          SolutionName      = '$(SolutionName)'
          EnvironmentName   = '$(EnvironmentName)'
          BicepFilePath     = './templates/main.infrastructure.bicep'
          TemplateOutFile   = './out/main.json'
      }
      $output = 'something'
      # $output = .\Deploy-Infrastructure.ps1 @deploymentArgs -Verbose
      Write-Host "##vso[task.setvariable variable=deploymentOutput;isOutput=true]$output"
      $output
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
    workingDirectory: 'deployment'

- task: AzurePowerShell@5
  displayName: 'Deploy dapr components'
  inputs:
    azureSubscription: 'azuredevops-giovanidecusati-spn'
    ScriptType: 'InlineScript'
    Inline: |
      $output = $(stepDeployInfrastructure.deploymentOutput)
      $output
      # $deploymentArgs = @{
      #     SubscriptionId            = '$(SubscriptionId)'
      #     ResourceGroupName         = '$(ResourceGroupName)'
      #     SolutionName              = '$(SolutionName)'
      #     ContainerAppEnvironment   = $output.Outputs.containerAppEnvironment.name
      #     ComponentsDirectory       = 'deployment/components'
      # }
      # .\Deploy-Dapr.ps1 @deploymentArgs -Verbose
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
    workingDirectory: 'deployment'